[package]
name = "valuator"
version = "0.1.0"
authors = ["Jimmie Elvenmark <flugsio@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
