#[allow(dead_code)]
#[derive(Clone, PartialEq, Eq, Ord, PartialOrd)]
pub enum Kind {
    Acorns,
    Algae,
    Beer,
    Bees,
    Biogas,
    Birds,
    Blank,
    Bread,
    Civic,
    CoffeeBeans,
    CoffeeCherry,
    Community,
    Consumer,
    Corn,
    CottonBale,
    Culture,
    Data,
    Devices,
    Eggs,
    Electricity,
    Entertainment,
    Ethanol,
    Fabric,
    Fertilizer,
    Fish,
    Fitness,
    FreshAir,
    Fruit,
    Fungi,
    Garment,
    Grapes,
    GreenhouseGas,
    Greywater,
    Groundwater,
    Hervibores,
    HotWater,
    InorganicWaste,
    Insects,
    Iron,
    Juice,
    Knowledge,
    Labor,
    Leather,
    Leisure,
    Livestock,
    Meat,
    Media,
    Milk,
    Money,
    Oil,
    Olives,
    OrganicWaste,
    Performer,
    Pesticides,
    Plastics,
    Pollution,
    Predators,
    ProcessedFood,
    RawCotton,
    RawMaterials,
    Rice,
    Risk,
    RoastedCoffee,
    Saltwater,
    Sickness,
    SocialCapital,
    SortedWaste,
    Steel,
    Sunlight,
    Technology,
    Tourist,
    Vegetables,
    Water,
    Wheat,
    Wilderness,
    Wine,
    Wood,
    Wool,
    Youth,
}

impl Kind {
    pub fn name(&self) -> String {
        match *self {
            Kind::Acorns => "Acorns",
            Kind::Algae => "Algae",
            Kind::Beer => "Beer",
            Kind::Bees => "Bees",
            Kind::Biogas => "Biogas",
            Kind::Birds => "Birds",
            Kind::Blank => "Blank",
            Kind::Bread => "Bread",
            Kind::Civic => "Civic",
            Kind::CoffeeBeans => "Coffee Beans",
            Kind::CoffeeCherry => "Coffee Cherry",
            Kind::Community => "Community",
            Kind::Consumer => "Consumer",
            Kind::Corn => "Corn",
            Kind::CottonBale => "Cotton Bale",
            Kind::Culture => "Culture",
            Kind::Data => "Data",
            Kind::Devices => "Devices",
            Kind::Eggs => "Eggs",
            Kind::Electricity => "Electricity",
            Kind::Entertainment => "Entertainment",
            Kind::Ethanol => "Ethanol",
            Kind::Fabric => "Fabric",
            Kind::Fertilizer => "Fertilizer",
            Kind::Fish => "Fish",
            Kind::Fitness => "Fitness",
            Kind::FreshAir => "Fresh Air",
            Kind::Fruit => "Fruit",
            Kind::Fungi => "Fungi",
            Kind::Garment => "Garment",
            Kind::Grapes => "Grapes",
            Kind::GreenhouseGas => "Greenhouse Gas",
            Kind::Greywater => "Greywater",
            Kind::Groundwater => "Groundwater",
            Kind::Hervibores => "Hervibores",
            Kind::HotWater => "Hot Water",
            Kind::InorganicWaste => "Inorganic Waste",
            Kind::Insects => "Insects",
            Kind::Iron => "Iron",
            Kind::Juice => "Juice",
            Kind::Knowledge => "Knowledge",
            Kind::Labor => "Labor",
            Kind::Leather => "Leather",
            Kind::Leisure => "Leisure",
            Kind::Livestock => "Livestock",
            Kind::Meat => "Meat",
            Kind::Media => "Media",
            Kind::Milk => "Milk",
            Kind::Money => "Money",
            Kind::Oil => "Oil",
            Kind::Olives => "Olives",
            Kind::OrganicWaste => "Organic Waste",
            Kind::Performer => "Performer",
            Kind::Pesticides => "Pesticides",
            Kind::Plastics => "Plastics",
            Kind::Pollution => "Pollution",
            Kind::Predators => "Predators",
            Kind::ProcessedFood => "Processed Food",
            Kind::RawCotton => "Raw Cotton",
            Kind::RawMaterials => "Raw Materials",
            Kind::Rice => "Rice",
            Kind::Risk => "Risk",
            Kind::RoastedCoffee => "Roasted Coffee",
            Kind::Saltwater => "Saltwater",
            Kind::Sickness => "Sickness",
            Kind::SocialCapital => "Social Capital",
            Kind::SortedWaste => "Sorted Waste",
            Kind::Steel => "Steel",
            Kind::Sunlight => "Sunlight",
            Kind::Technology => "Technology",
            Kind::Tourist => "Tourist",
            Kind::Vegetables => "Vegetables",
            Kind::Water => "Water",
            Kind::Wheat => "Wheat",
            Kind::Wilderness => "Wilderness",
            Kind::Wine => "Wine",
            Kind::Wood => "Wood",
            Kind::Wool => "Wool",
            Kind::Youth => "Youth",
        }.to_string()
    }
}
